version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
    networks:
      - webdemo-network

  api:
    build:
      context: .
      dockerfile: ./InWestyGator.WebDemo/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - webdemo-network

networks:
  webdemo-network:
    driver: bridge
